// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.xsgj.proto.user;

public interface UserIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xsgj.UserId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
